name: Build, Push and Update GitOps

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::971691552202:role/atpl-github-avangelsin-role
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set Image Tag
        run: echo "IMAGE_TAG=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build and Push Image
        run: |
          docker build -t test-app:${IMAGE_TAG} .
          docker tag test-app:${IMAGE_TAG} \
          971691552202.dkr.ecr.ap-south-1.amazonaws.com/atpl/avangelsin/test-app:${IMAGE_TAG}
          docker push 971691552202.dkr.ecr.ap-south-1.amazonaws.com/atpl/avangelsin/test-app:${IMAGE_TAG}

      # -----------------------------
      # GitOps Automation Starts Here
      # -----------------------------

      - name: Checkout Tenants Repo
        uses: actions/checkout@v4
        with:
          repository: avangels-tech/tenants
          token: ${{ secrets.TENANTS_REPO_TOKEN }}
          path: tenants-repo

      - name: Update Image in GitOps
        run: |
          cd tenants-repo/avangelsin
          sed -i "s|image: .*test-app:.*|image: 971691552202.dkr.ecr.ap-south-1.amazonaws.com/atpl/avangelsin/test-app:${IMAGE_TAG}|g" test-app-deployment.yaml

      - name: Commit and Push GitOps Change
        run: |
          cd tenants-repo
          git config user.name "ATPL CI"
          git config user.email "ci@atpl.local"
          git add .
          git commit -m "Update avangelsin test-app image to ${IMAGE_TAG}" || echo "No changes to commit"
          git push

